source "http://rubygems.org"

gem "rails", "3.0.5" #, :path => "~/projects/other_apps/rails"
gem "mysql"

# gem "authlogic"
# TODO this is temporary until the official authlogic gem is updated for rails 3
gem 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'

gem "disguise"
gem "bcrypt-ruby", :require => "bcrypt"
gem "jammit"

gem "muck-engine", :path => "../"
gem "muck-users", :path => "~/projects/muck-users"

if RUBY_VERSION < "1.9"
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails", ">=2.4.0"
  gem "cucumber-rails"
end

group :test do
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.4.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end
