source :gemcutter

gem "rails", "2.3.5"
gem 'mysql'
gem 'ruby-debug'
gem "authlogic", '2.1.3'

gem 'ruby-debug'
gem 'mocha', '>= 0.9.8'
gem 'redgreen'
gem 'factory_girl'
gem 'shoulda'
gem 'treetop', '>=1.2.4'
gem 'term-ansicolor', '>=1.0.3', :require => 'term/ansicolor'
gem 'cucumber', '>=0.1.13', :require => 'cucumber'
gem 'polyglot', '>=0.2.4'
gem "rcov", '>=0.8.1.2.0'
gem "webrat", '>=0.4.4'
gem 'redgreen'

# gem 'rspec', '>=1.1.12', :require_as => 'spec'
# gem 'rspec-rails', '>=1.1.12', :require_as => 'spec/rails'
# only required if you want to use selenium for testing
# gem 'selenium-client', :require_as => 'selenium/client'
# gem 'database_cleaner'

gem 'muck-users', '0.3.13', :require => 'muck_users'
gem 'muck-engine', :require => 'muck_engine', :path => File.join(File.dirname(__FILE__), *%w(.. .. ..))
# gem 'muck-engine', :require => 'muck_engine', :path => "~/projects/muck-engine"
# gem 'muck-users', :require => 'muck_users', :path => "~/projects/muck-users"