source "http://rubygems.org"

gem "rails", "3.0.0" #, :path => "~/projects/other_apps/rails"
gem "mysql"

# gem "authlogic"
# TODO this is temporary until the official authlogic gem is updated for rails 3
gem "authlogic", :git => "git://github.com/odorcicd/authlogic.git", :branch => "rails3"

gem "disguise"
gem "bcrypt-ruby", :require => "bcrypt"
gem "overlord"

gem "muck-engine", :path => "../../"
gem "muck-users", :path => "~/projects/muck-users"

if RUBY_VERSION < "1.9"
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails", ">=2.0.0"
  gem "cucumber-rails"
end

group :test do
  gem "autotest"
  gem "capybara", ">= 0.3.9"
  # this is also temporary until shoulda works with Rails 3. Local version includes this fix: http://github.com/dchelimsky/shoulda/commit/586b2d90e277c11f951180a203cc92292ff01026
  gem "shoulda", :path => "~/projects/other_apps/shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.0.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end
