source "http://rubygems.org"

gem "rails", "3.0.0"
gem "capybara", ">= 0.3.9"
gem 'mysql'

# gem 'authlogic'
# TODO this is temporary until the official authlogic gem is updated for rails 3
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'

gem 'disguise'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'overlord'

gem 'muck-engine', :require => 'muck_engine', :path => '../../'
gem 'muck-users', :require => 'muck_users', :path => "~/projects/muck-users"

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test do
  gem 'shoulda'
  gem 'factory_girl'
  gem 'mocha'
  gem 'redgreen'
  gem 'cucumber'
  gem 'webrat'
  gem 'rspec'
  gem 'rspec-rails'
  # only required if you want to use selenium for testing
  # gem 'selenium-client', :require_as => 'selenium/client'
  # gem 'database_cleaner'
end